services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
      - ./wk:/work
    depends_on:
      - php

  php:
    build: ./php
    volumes:
      - ./html:/var/www/html
      - ./wk:/work
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - 13306:3306
    volumes:
      - ./db/data:/var/lib/mysql
      - ./wk:/work
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    volumes:
      - ./wk:/work
    depends_on:
      - db
